baseURL = 'https://vitistack.io/'
languageCode = 'en-us'
title = 'Vitistack - Kubernetes Infrastructure Platform'

[params]
  description = "Infrastructure platform for delivering Kubernetes platforms programmatically"
  author = "Vitistack"
